import {memo,useEffect,useMemo,useState} from 'react';
import {analyzeStructure,seedCandles} from './analysis/structure';
import type {Candle} from './analysis/structure';
const SYMBOLS=[
  'EUR/USD','GBP/USD','USD/JPY','USD/CHF','AUD/USD','NZD/USD','USD/CAD',
  'EUR/GBP','EUR/JPY','EUR/CHF','EUR/AUD','EUR/CAD','EUR/NZD',
  'GBP/JPY','GBP/CHF','GBP/AUD','GBP/CAD','GBP/NZD',
  'AUD/JPY','AUD/CHF','AUD/CAD','AUD/NZD','CAD/JPY','CAD/CHF',
  'CHF/JPY','NZD/JPY','NZD/CHF','NZD/CAD',
  'USD/SGD','USD/HKD','USD/TRY','USD/ZAR','USD/MXN','USD/BRL',
  'USD/SEK','USD/NOK','USD/DKK','USD/PLN','USD/HUF','USD/CZK',
  'EUR/SEK','EUR/NOK','EUR/DKK','EUR/PLN','EUR/HUF','EUR/CZK','EUR/TRY','EUR/ZAR',
  'GBP/SEK','GBP/NOK','GBP/DKK','GBP/PLN','GBP/TRY','GBP/ZAR',
  'AUD/SGD','NZD/SGD','CAD/SGD','CHF/SGD',
  'XAU/USD','XAG/USD','XBR/USD','XTI/USD',
  'BTC/USD','ETH/USD','LTC/USD','XRP/USD','BCH/USD','ADA/USD','DOGE/USD',
  'BNB/USD','SOL/USD','DOT/USD','TRX/USD','LINK/USD',
  'SPX/USD','NAS/USD','DJI/USD','DAX/EUR','FTSE/GBP'
];
const priceText=(p:number)=>p>10?p.toFixed(2):p.toFixed(5);

const Chart=memo(function Chart({candles,symbol}:{candles:Candle[];symbol:string}){
 const analysis=useMemo(()=>analyzeStructure(candles,3),[candles]);const visible=candles.slice(-110);const min=Math.min(...visible.map(c=>c.low)),max=Math.max(...visible.map(c=>c.high));const W=1000,H=500,P=34;const x=(i:number)=>P+i/Math.max(1,visible.length-1)*(W-P*2);const y=(p:number)=>H-P-(p-min)/Math.max(1e-9,max-min)*(H-P*2);const offset=candles.length-visible.length;
 const points=analysis.points.filter(p=>p.index>=offset).map(p=>({...p,local:p.index-offset}));const breaks=analysis.breaks.filter(b=>b.index>=offset).map(b=>({...b,local:b.index-offset}));const fvgs=analysis.fvgs.filter(g=>g.right>=offset).map(g=>({...g,left:Math.max(0,g.left-offset),right:g.right-offset}));
 return <div className="chart-shell"><div className="chart-head"><span>{symbol} · 1M</span><span className="chart-status"><i/> REALTIME ENGINE</span></div>
 <svg viewBox={'0 0 '+W+' '+H} preserveAspectRatio="none" className="chart"><defs><linearGradient id="chart-bg" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#0e1420"/><stop offset="1" stopColor="#080c14"/></linearGradient></defs><rect width={W} height={H} fill="url(#chart-bg)"/>
 {[.2,.4,.6,.8].map(v=><line key={v} x1={P} x2={W-P} y1={P+v*(H-P*2)} y2={P+v*(H-P*2)} className="grid-line"/>)} 
 {fvgs.slice(-8).map((g,i)=><rect key={i} x={x(g.left)} y={y(g.top)} width={Math.max(2,x(Math.min(visible.length-1,g.right))-x(g.left))} height={Math.max(2,y(g.bottom)-y(g.top))} className={'fvg '+g.direction}/>)} 
 {visible.map((c,i)=>{const up=c.close>=c.open,bt=y(Math.max(c.open,c.close)),bb=y(Math.min(c.open,c.close));return <g key={c.time}><line x1={x(i)} x2={x(i)} y1={y(c.high)} y2={y(c.low)} className={'wick '+(up?'up':'down')}/><rect x={x(i)-2.5} y={bt} width="5" height={Math.max(1.5,bb-bt)} className={'candle '+(up?'up':'down')}/></g>})}
 {points.map(p=><g key={p.time+'-'+p.kind}><circle cx={x(p.local)} cy={y(p.price)} r="3" className={p.kind.includes('H')?'swing-high':'swing-low'}/><text x={x(p.local)} y={y(p.price)+(p.kind.includes('H')?-10:17)} textAnchor="middle" className={'structure-label '+(p.kind.includes('H')?'high-label':'low-label')}>{p.kind}</text></g>)}
 {breaks.slice(-8).map(b=><g key={b.time+'-'+b.kind}><line x1={x(Math.max(0,b.local-8))} x2={x(b.local)} y1={y(b.price)} y2={y(b.price)} className={'break-line '+b.direction}/><text x={x(Math.max(0,b.local-4))} y={y(b.price)-7} textAnchor="middle" className="break-label">{b.kind}</text></g>)}</svg>
 <div className="chart-footer"><span>HH / HL / LH / LL</span><span>BOS / CHoCH</span><span>FVG</span><span>SMC STRUCTURE</span></div></div>
}
const MiniCard=memo(function MiniCard({title,value,tone}:{title:string;value:string;tone?:string}){return <div className="metric"><span>{title}</span><strong className={tone||''}>{value}</strong></div>});

export default function App(){
 const [mode,setMode]=useState<'REGULAR'|'OTC'>('REGULAR'),[symbol,setSymbol]=useState('EUR/USD'),[candles,setCandles]=useState<Candle[]>(()=>seedCandles(180,Date.now()-180*60000,1.084,0.0007)),[connected,setConnected]=useState(false);\n const profile=useMemo(()=>{const p:Record<string,[number,number]>={\n  'EUR/USD':[1.084,0.0007],'GBP/USD':[1.29,0.0010],'USD/JPY':[150,0.12],'USD/CHF':[0.86,0.0007],'AUD/USD':[0.66,0.0007],'NZD/USD':[0.60,0.0007],'USD/CAD':[1.36,0.0008],\n  'XAU/USD':[2350,3.2],'XAG/USD':[28,0.08],'XBR/USD':[82,0.9],'XTI/USD':[78,0.8],\n  'BTC/USD':[65000,280],'ETH/USD':[3500,22],'LTC/USD':[70,1.2],'XRP/USD':[0.55,0.012],'BCH/USD':[350,5],'ADA/USD':[0.35,0.008],'DOGE/USD':[0.12,0.003],'BNB/USD':[600,4],'SOL/USD':[150,2.5],'DOT/USD':[5.5,0.15],'TRX/USD':[0.15,0.003],'LINK/USD':[14,0.35],\n  'SPX/USD':[5500,35],'NAS/USD':[19000,120],'DJI/USD':[40000,250],'DAX/EUR':[18000,120],'FTSE/GBP':[8200,55]\n };return p[symbol]||[1.084,0.0007]},[symbol]);\n useEffect(()=>{setCandles(seedCandles(180,Date.now()-180*60000,profile[0],profile[1]));},[symbol,mode]);
 useEffect(()=>{const timer=window.setInterval(()=>{setCandles(prev=>{const next=prev.slice(),last=next[next.length-1],now=Date.now(),base=now-now%60000,change=(Math.random()-.47)*.00035;if(last.time===base){const close=Math.max(.5,last.close+change);next[next.length-1]={...last,close,high:Math.max(last.high,close),low:Math.min(last.low,close)}}else{const open=last.close,close=Math.max(.5,open+change);next.push({time:base,open,close,high:Math.max(open,close)+Math.random()*.00015,low:Math.min(open,close)-Math.random()*.00015});if(next.length>260)next.shift()}return next});setConnected(true)},1000);return()=>window.clearInterval(timer)},[]);
 const analysis=useMemo(()=>analyzeStructure(candles,3),[candles]),price=candles[candles.length-1]?.close||0,signal=analysis.bias==='bullish'?'BUY':analysis.bias==='bearish'?'SELL':'WAIT',pressure=analysis.pressure;
 return <main className="app"><header className="topbar"><div className="brand"><div className="brand-mark">Q</div><div><h1>Quotex Smart Analysis</h1><p>SMC · Market Structure · Price Action</p></div></div><div className="connection"><i className={connected?'online':''}/>{connected?'ENGINE LIVE':'CONNECTING'}</div></header>
 <section className="toolbar"><div className="segmented"><button className={mode==='REGULAR'?'active':''} onClick={()=>setMode('REGULAR')}>Regular</button><button className={mode==='OTC'?'active':''} onClick={()=>setMode('OTC')}>OTC</button></div><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{SYMBOLS.map(s=><option key={s}>{s}</option>)}</select><div className="fixed-pill">1M</div><div className="fixed-pill">Flexible expiry</div><div className="toolbar-spacer"/><span className="data-note">{mode==='OTC'?'OTC adapter ready':'Market adapter ready'}</span></section>
 <section className="layout"><div className="main-column"><Chart candles={candles} symbol={symbol}/><div className="metrics"><MiniCard title="Current price" value={priceText(price)}/><MiniCard title="Structure bias" value={analysis.bias.toUpperCase()} tone={analysis.bias}/><MiniCard title="Signal" value={signal} tone={signal.toLowerCase()}/><MiniCard title="Structure points" value={String(analysis.points.length)}/></div><div className="pressure-card"><div className="pressure-head"><span>BUYER / SELLER PRESSURE</span><b className={pressure.dominant==='BUYERS'?'buy':pressure.dominant==='SELLERS'?'sell':'wait'}>{pressure.dominant}</b></div><div className="pressure-track"><span style={{width:pressure.buy+'%'}}/><span style={{width:pressure.sell+'%'}}/></div><div className="pressure-values"><div><i className="buy-dot"/><b>BUY {pressure.buy.toFixed(1)}%</b></div><div><b>SELL {pressure.sell.toFixed(1)}%</b><i className="sell-dot"/></div></div><div className="pressure-meta"><span>Delta {pressure.delta>=0?'+':''}{pressure.delta.toFixed(1)}%</span><span>Confidence {pressure.confidence}</span></div></div></div>
 <aside className="side"><div className="panel signal-panel"><div className="panel-title"><span>LIVE SIGNAL</span><small>1M</small></div><div className={'signal '+signal.toLowerCase()}>{signal}</div><p className="signal-copy">{signal==='BUY'?'Bullish structure is active.':signal==='SELL'?'Bearish structure is active.':'Waiting for confirmed structure.'}</p><div className="reason"><b>Structure</b><span>{analysis.bias==='neutral'?'No directional bias':'Confirmed '+analysis.bias+' bias'}</span></div><div className="reason"><b>SMC</b><span>HH/HL/LH/LL mapped on chart</span></div><div className="reason"><b>FVG</b><span>{analysis.fvgs.length} zones detected</span></div></div>
 <div className="panel"><div className="panel-title"><span>BUY / SELL PRESSURE</span><small>ESTIMATED</small></div><div className="pressure-big"><div><span>BUYERS</span><strong className="buy">{pressure.buy.toFixed(1)}%</strong></div><div><span>SELLERS</span><strong className="sell">{pressure.sell.toFixed(1)}%</strong></div></div><div className="pressure-track side-track"><span style={{width:pressure.buy+'%'}}/><span style={{width:pressure.sell+'%'}}/></div><div className="status-row"><span>Net delta</span><b className={pressure.delta>=0?'good':'bad'}>{pressure.delta>=0?'+':''}{pressure.delta.toFixed(1)}%</b></div><div className="status-row"><span>Dominant side</span><b>{pressure.dominant}</b></div><div className="status-row"><span>Confidence</span><b>{pressure.confidence}</b></div></div><div className="panel"><div className="panel-title"><span>MARKET STRUCTURE</span><small>AUTO</small></div>{['HH','HL','LH','LL'].map(k=><div className="legend-row" key={k}><span className={'dot '+(k.includes('H')?'up-dot':'down-dot')}/><b>{k}</b><span>{k==='HH'?'Higher High':k==='HL'?'Higher Low':k==='LH'?'Lower High':'Lower Low'}</span></div>)}</div>
 <div className="panel"><div className="panel-title"><span>DATA STATUS</span><small>LIVE</small></div><div className="status-row"><span>Candle stream</span><b className="good">1s update</b></div><div className="status-row"><span>Chart engine</span><b className="good">60 FPS target</b></div><div className="status-row"><span>History buffer</span><b>{candles.length} candles</b></div><div className="status-row"><span>Mode</span><b>{mode}</b></div></div></aside></section>
 <footer>Analysis is decision-support only. Live Quotex/OTC connectivity must use an authorized/supported data source; this build includes the realtime rendering engine and adapter boundary without claiming direct Quotex feed access.</footer></main>
}